add_newline = false

format = """
$directory$git_branch$git_status$python$nodejs$golang$character"""

[directory]
format = "[$path]($style) "
style = "bold #66d9ef"
truncation_length = 2
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "#a6e22e"
format = "[$symbol$branch]($style) "

[git_status]
style = "#f92672"
format = "[$all_status$ahead_behind]($style) "

[python]
symbol = ""
style = "#e6db74"
format = "[$symbol$version]($style) "

[nodejs]
symbol = ""
style = "#a6e22e"
format = "[$symbol$version]($style) "

[golang]
symbol = ""
style = "#66d9ef"
format = "[$symbol$version]($style) "

[character]
success_symbol = "[](bold #66d9ef)"
error_symbol = "[](bold #f92672)"
